Pause indicator
code-dot-org/code-dot-org pull request #28637
Opened 2019-05-18 00:39 UTC by larrypo

Adds an icon to help indicate breakpoints. Also puts the breakpoint color behind the breakpoint, error, and warning icons. 

This is for https://codedotorg.atlassian.net/browse/STAR-196

![Screen Shot 2019-05-17 at 4 12 10 PM](https://user-images.githubusercontent.com/11651276/57962355-a0528400-78ca-11e9-94ad-1b7ba7da887d.png)

2019-05-20 21:11 UTC, islemaster requested changes
Hey Larry!  This looks great in text mode, but the pause icon isn't centered in block mode (at least on my machine - not sure how much this will vary from browser to browser).  I know the warning icon't isn't centered either, but while you're in there, can we see if we can get it looking great in both scenarios?

![Peek 2019-05-20 14-07](https://user-images.githubusercontent.com/1615761/58052240-222ff080-7b09-11e9-8f45-2b4468bd4d90.gif)

2019-05-20 21:11 UTC, islemaster commented on apps/style/common.scss
> +// By being defined before the rulthe pause icones for ace_warning and ace_error, the warning and error icons will take
Looks like a little content got lost in this comment.

2019-05-24 22:21 UTC, larrypo commented on apps/style/common.scss
> +// By being defined before the rulthe pause icones for ace_warning and ace_error, the warning and error icons will take
Fixed.

2019-05-25 00:54 UTC, islemaster approved these changes
:tada: Looks awesome Larry!

2019-05-25 00:54 UTC, merged

2019-05-28 17:26 UTC, ryansloan commented
Just saw that this is live in Staging! :tada: Woohoo!