Add ExternalMarkdown DSL content to I18n Sync
code-dot-org/code-dot-org pull request #28987
Opened 2019-06-06 23:59 UTC by Hamms

2019-06-14 16:53 UTC, davidsbailey approved these changes

2019-06-17 20:31 UTC, joshlory requested changes
Should this be scoped to only CSF levels? I see a lot of CSD and PD strings that I don't think we want to translate.

2019-06-18 16:48 UTC, Hamms commented
According to https://docs.google.com/spreadsheets/d/1ygjTkqyJMNZwTYVT1RB3LCIc4UeVLswSbvn5VZHB_L0/edit#gid=0, we _do_ want to translate those

2019-06-20 02:37 UTC, joshlory approved these changes
TIL.

2019-07-11 20:12 UTC, merged