[Data Viz] Implement Scatter Plot Chart type
code-dot-org/code-dot-org pull request #31437
Opened 2019-10-23 21:30 UTC by ajpal

# Description
Implements the scatter plot view:
![image](https://user-images.githubusercontent.com/8787187/67435737-a64b4000-f5a1-11e9-976d-d277c07f8bb4.png)

## Links

- [spec](https://docs.google.com/document/d/1s1CQ4SSrpwJtLwI5gJoFzJEbcEXZHQIQ6ikAxB9H3j4/edit)
- [jira](https://codedotorg.atlassian.net/browse/STAR-753)

## Testing story

# Reviewer Checklist:

- [ ] Tests provide adequate coverage
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

2019-10-23 22:03 UTC, islemaster reviewed
Unit test?

2019-10-31 19:06 UTC, jmkulwik approved these changes
LGTM!

2019-10-31 19:10 UTC, islemaster requested changes

2019-10-31 19:10 UTC, islemaster commented on apps/test/unit/storage/dataBrowser/DataVisualizerTest.js
> +    afterEach(() => spy.restore());
Please update this test to clean up the DOM.

2019-10-31 20:40 UTC, islemaster approved these changes
:tada:

2019-11-04 18:32 UTC, merged