State management for Data Visualizer
code-dot-org/code-dot-org pull request #32443
Opened 2019-12-17 19:02 UTC by ajpal

# Description
- clear all state when `this.props.tableName` changes, using React key
- clear selected columns when chart type changes
- clear filter value when filter column changes

## Testing story

# Reviewer Checklist:

- [ ] Tests provide adequate coverage
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

2019-12-17 20:12 UTC, islemaster commented on apps/src/storage/dataBrowser/TableControls.jsx
> +            <VisualizerModal key={this.props.tableName} />
Interesting!  I hadn't seen `key` used this way before, so I did some digging and learned that this is the ["Fully uncontrolled component with a `key`"](https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html#recommendation-fully-uncontrolled-component-with-a-key) pattern, recommended [by the React docs](https://reactjs.org/docs/react-component.html#static-getderivedstatefromprops) when "you want to 'reset' some state when a prop changes."  Great find!

2019-12-17 20:16 UTC, islemaster requested changes
There are three new behaviors in this PR.  Please cover them with new unit tests.  Otherwise, this looks great!  It feels like you've built a component that's easy to change. :+1:

2019-12-19 21:34 UTC, islemaster commented on apps/test/unit/storage/dataBrowser/TableControlsTest.js
> +      })
Wow!  Looks like there were some tricky problems to solve writing this test.  Nice work.

One thing I like to explore when actions and assertions start getting verbose like this is extracting helper methods just to make the test easier to read. I've added a couple of commits to do that, and make the assertions align a little better with the idea of the state being fully reset.  Let me know what you think.

2019-12-19 21:35 UTC, islemaster approved these changes
Great work!

2019-12-19 21:36 UTC, epeach approved these changes
LGTM

2019-12-19 23:12 UTC, merged