Fix minimum requirement logic in teacher application
code-dot-org/code-dot-org pull request #32551
Opened 2020-01-07 10:15 UTC by hacodeorg

…ents

# Description

## Links

- [spec]()
- [jira]()

## Testing story

# Reviewer Checklist:

- [ ] Tests provide adequate coverage
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

2020-01-07 18:22 UTC, agealy approved these changes
Thanks for the quick fix!

2020-01-07 23:02 UTC, islemaster requested changes
This won't work because the `principal_wont_replace_existing_course` value (which also has a misleading name) is a composed value and won't be an exact match for the `YES` constant.

First, note that this question gets asked on both the teacher application and the principal approval form, that either can impact autoscoring and the principal's answer should "win" if they conflict.

Second, the question text on the principal approval form is:

> Will this course replace an existing computer science course in the master schedule? If yes, please list the course(s) that will be replaced.

Unfortunately the answer we're checking includes that "list the courses" part. Here, after the principal approval is created, the `replace_course`, `replace_course_other`, and `replace_which_course*` fields all get combined and stored as `replace_course_string`

https://github.com/code-dot-org/code-dot-org/blob/f548aa8d16fe29b835ad83cd922dc6a8d3028fdb/dashboard/app/models/pd/application/teacher2021_application.rb#L913-L916

Which is eventually stored as `principal_wont_replace_existing_course`

https://github.com/code-dot-org/code-dot-org/blob/f548aa8d16fe29b835ad83cd922dc6a8d3028fdb/dashboard/app/models/pd/application/teacher2021_application.rb#L948

So I think for this logic to work, you'll want to make sure the principal approval part of the scoring logic checks that the answer starts with yes, not that it's exactly equal.

Please add unit tests for this behavior - the ones that exist don't cover this very well.  Here's an example test case, but it doesn't use a realistic `principal_wont_replace_existing_course` value. I'd like to see a few test cases covering the outcomes you describe in the PR description.

```rb
    test 'autoscore: does not meet minimum requirements if we will replace an existing CS course' do
      application_hash = build :pd_teacher2021_application_hash,
        program: Pd::Application::TeacherApplicationBase::PROGRAMS[:csp],
        replace_existing: YES,
        principal_wont_replace_existing_course: YES

      application = create :pd_teacher2021_application, regional_partner: (create :regional_partner), form_data_hash: application_hash
      application.auto_score!

      assert_equal(
        NO,
        JSON.parse(application.response_scores)['meets_minimum_criteria_scores']['replace_existing']
      )
    end
```

Thanks!

2020-01-08 10:10 UTC, hacodeorg commented
Thank you for catching this issue 🤦‍♂ Will fix!

2020-01-16 23:28 UTC, islemaster commented on dashboard/test/models/pd/application/teacher2021_application_test.rb
> +    end
What a test!
![combo_super_combo_finish](https://user-images.githubusercontent.com/1615761/72571518-adb67880-3874-11ea-9b78-2229773f32b6.jpg)

2020-01-16 23:28 UTC, islemaster approved these changes
:+1: Nicely done!

2020-01-20 18:23 UTC, merged