s/defintions/definitions
code-dot-org/code-dot-org pull request #34735
Opened 2020-05-11 15:22 UTC by bethanyaconnor

🤦‍♀️ 🤦‍♀️ 🤦‍♀️ 🤦‍♀️ 🤦‍♀️ 🤦‍♀️ 🤦‍♀️ 

I'll need to do another round of deduplication to fix

## Links

- [spec]()
- [jira]()

## Testing story

# Reviewer Checklist:

- [ ] Tests provide adequate coverage
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

2020-05-11 16:58 UTC, daynew requested changes
Do you also need to change line 78?
```
i18n_strings['function_defintions'] = Hash.new unless functions.empty?
```

2020-05-11 16:58 UTC, Hamms approved these changes
hah, oops!

2020-05-11 17:32 UTC, bethanyaconnor commented
Great catch @daynew

2020-05-12 17:04 UTC, daynew approved these changes

2020-05-13 18:01 UTC, merged