Remove encryption key
code-dot-org/code-dot-org pull request #35106
Opened 2020-06-03 00:14 UTC by dmcavoy

## Links

- [spec]()
- [jira]()

## Testing story

# Reviewer Checklist:

- [ ] Tests provide adequate coverage
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

2020-06-03 17:29 UTC, uponthesun approved these changes
I think this is a good step, though it probably isn't foolproof because I think drone seeds a subset of everything so it goes faster.

2020-06-03 17:32 UTC, davidsbailey approved these changes
that's a good point @uponthesun . a contributor might still run into problems, in which case we could suggest trying `rake seed:ui_test` as a workaround.

2020-06-03 17:35 UTC, davidsbailey requested changes
actually, wait -- the drone run didn't do any seeding:
```
Finished seed:cached_ui_test (18 seconds)
```
this logic controls whether it does any seeding or not: https://github.com/code-dot-org/code-dot-org/blob/d57211e76b40247f61161d9b8070ec96a4a9402c/dashboard/lib/tasks/seed.rake#L352-L374

@dmcavoy I would suggest making a temporary change to that logic to force drone to actually re-seed, as opposed to using the cached copy (which I'm assuming it used since it finished so quickly).

2020-06-03 17:39 UTC, davidsbailey commented
@uponthesun , I ran into a similar problem recently while changing seeding logic in script.rb. would it make sense for us to expand the watched files list to include more files which affect seeding? alternately, we could also add a manual override to force re-seeding, but maybe we can defer that until a time where adding files to the watch list doesn't make sense.

2020-06-03 17:46 UTC, davidsbailey commented
some files which I think should be added to the watcher list:
```
dashboard/app/models/script.rb
dashboard/lib/level_loader.rb
docker/ui_tests.sh
```

2020-06-03 20:49 UTC, davidsbailey commented
@dmcavoy no rush, but if you're looking to move this forward before we sort out the long term plan, could you please do so by adding `'docker/ui_tests.sh'` to the list of `watched_files`? that should be enough to cause a non-cached rake seed to happen.

2020-06-08 13:23 UTC, dmcavoy commented
@davidsbailey @uponthesun should I wait on this change until we decide if more files should be included in the watched files list for seeding?

2020-06-08 15:35 UTC, dmcavoy commented
> @davidsbailey @uponthesun should I wait on this change until we decide if more files should be included in the watched files list for seeding?

Sorry just saw Dave's comment. For some reason it did not load before.

2020-06-30 16:53 UTC, closed without merging