Update sections redux when the teacher adds/removes students
code-dot-org/code-dot-org pull request #36705
Opened 2020-09-10 22:28 UTC by jmkulwik

## Links

- [spec]()
- [jira]()

## Testing story

# Reviewer Checklist:

- [ ] Tests provide adequate coverage
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

2020-09-11 23:21 UTC, cforkish requested changes
looking at this code always gives me so uncomfortable (not yours, just our redux stuff in general). that said, this looks like a good solution.

one minor change request: i don't think you want to merge your schema_cache.dump, do you?

2020-09-14 20:36 UTC, clareconstantine approved these changes
This seems like a good way to keep things up to date given the current messy state of this redux system.

2020-09-17 01:39 UTC, jmkulwik commented
Force-push was a rebase onto staging

2020-09-17 22:52 UTC, molly-moen commented on apps/test/unit/templates/manageStudents/ManageStudentsActionsCellTest.js
> +// import * as sectionData from '@cdo/apps/redux/sectionDataRedux';
remove this comment?

2020-09-17 22:53 UTC, molly-moen approved these changes

2020-09-17 23:04 UTC, cforkish approved these changes

2020-09-18 00:06 UTC, jmkulwik commented on apps/test/unit/templates/manageStudents/ManageStudentsActionsCellTest.js
> +// import * as sectionData from '@cdo/apps/redux/sectionDataRedux';
Oh oops. Thank you!

2020-09-18 17:22 UTC, merged