About: fix external logo
code-dot-org/code-dot-org pull request #36943
Opened 2020-09-28 21:29 UTC by breville

The external logo was not always loading, and when it was, was not showing correctly.  Now, it's updated and served locally.

### before
![Screen Shot 2020-09-28 at 2 21 51 PM](https://user-images.githubusercontent.com/2205926/94488148-f578f800-0196-11eb-9fc5-2d4bd6aa1257.png)

### after
![Screen Shot 2020-09-28 at 2 24 46 PM](https://user-images.githubusercontent.com/2205926/94488150-f742bb80-0196-11eb-969b-f5490cb6cda0.png)

2020-09-28 22:00 UTC, clareconstantine approved these changes
should we be adding those security tags to other logos?

2020-09-28 22:00 UTC, clareconstantine commented on pegasus/sites.v3/code.org/public/about/index.erb.md.erb
> +<a href="https://www.guidestar.org/profile/46-0858543" target="_blank" rel="noopener noreferrer">
TIL: `rel="noopener noreferrer"` :)

2020-09-29 01:10 UTC, breville commented on pegasus/sites.v3/code.org/public/about/index.erb.md.erb
> +<a href="https://www.guidestar.org/profile/46-0858543" target="_blank" rel="noopener noreferrer">
I have been learning from @Hamms, including from [here](https://github.com/code-dot-org/code-dot-org/pull/36762#issuecomment-696393929).

2020-09-29 21:00 UTC, cforkish requested changes
thanks for jumping on this @breville! however, i would like to propose a few changes:

1) instead of this new b&w logo, how about using the gold one you found, since that's our current tier?
2) instead of setting it as the `img src`, how about setting it as the `background-image` so the dynamically-loaded one will still display in the non-failure case?
3) i discovered that changing `=v3` at the end of the url to `=v4` causes the image to render properly, so i think we should update that
4) it looks like we use this logo in four places, so let's update them all to be consistent:
```
pegasus/sites.v3/code.org/public/about/index.erb.md.erb
pegasus/sites.v3/code.org/public/alt-about/index.md.erb
pegasus/sites.v3/code.org/public/alt-about/our-impact.md
pegasus/sites.v3/code.org/public/donate/amazon.md
```
@breville i'm happy to take this over if you'd like, just let me know if so!

2020-09-29 21:13 UTC, cforkish commented on pegasus/sites.v3/code.org/public/about/index.erb.md.erb
> +<a href="https://www.guidestar.org/profile/46-0858543" target="_blank" rel="noopener noreferrer">
+1 :)

2020-09-29 22:34 UTC, breville commented
Thanks @clareconstantine.

1. If we are still "gold", then that sounds good.  It does seem to look nice at its native size:
![Screen Shot 2020-09-29 at 3 30 40 PM](https://user-images.githubusercontent.com/2205926/94623385-e6627a80-0268-11eb-9994-5b2a659fa6dc.png)
2. I'm not a big fan of having a fallback, because it means we'll have one path that isn't regularly exercised, and our one piece of coverage, the Eyes test, will also not cover both paths properly.  I'd much rather we just settle on one path that we are confident will always work.
3. If you're confident that's the right way to get consistent behaviour, then it sounds like a good stable path to pick.
4. Good call.  It looks like `alt-about` is some kind of in-progress content which hasn't been touched for a while, but it couldn't hurt to update it too.

And it would be great if you could take this on.  Happy to review.  Thanks!

2020-10-01 04:52 UTC, cforkish commented
>     1. If we are still "gold", then that sounds good.  It does seem to look nice at its native size:

we are still gold, but it turns out that image was outdated, so i updated to the latest one returned by the widget and removed the old one

>     2\. I'm not a big fan of having a fallback, because it means we'll have one path that isn't regularly exercised, and our one piece of coverage, the Eyes test, will also not cover both paths properly.  I'd much rather we just settle on one path that we are confident will always work.

my thoughts on this is that our primary source of the logo should definitely be the widget they provide for this purpose. the above example of us having a static asset that is outdated is a prime example of why. also since [that's how they tell us to do it](http://help.guidestar.org/en/articles/2160518-how-to-add-a-guidestar-participation-logo-to-a-website), it feels to me a little disrespectful to do otherwise.

however, their widget is flaky. in the case that it fails, i personally think it would be better to fall back to a static asset for two reasons: one, it looks better than the default broken image we are currently showing in that case, and two, it will provide a way of de-flaking the "about" page eyes test that doesn't require putting a big ignore region at the bottom, which imo is a cleaner solution.

error handling is usually (ideally) a code path that isn't regularly exercised, and to me this seems pretty similar. also, we know from the flaky test that both paths _do_ get tested, albeit not every time! ;-)

>     3\. If you're confident that's the right way to get consistent behaviour, then it sounds like a good stable path to pick.

i think the only single stable path we can be confident about would be only using the static image. if you think that single-and-stable should be the priority, i'm happy to update to that solution.

>     4\. Good call.  It looks like `alt-about` is some kind of in-progress content which hasn't been touched for a while, but it couldn't hurt to update it too.

yeah, also i'm not sure `amazon.md` is still used because code.org/donate redirects. but i updated just to be safe. i would prefer to remove them, but i'm not yet familiar enough with our codebase to figure out how to be certain something's not used anymore. =\

2020-10-01 04:54 UTC, cforkish approved these changes

2020-10-01 04:56 UTC, cforkish commented
@breville i guess i can't request your review since this is your PR, but i would love to get your eyes and thoughts on what i pushed! :)

2020-10-02 00:27 UTC, breville commented on pegasus/sites.v3/code.org/public/alt-about/index.md.erb
> +</a>
It might be good to factor this common content out into an embeddable view/partial.

2020-10-02 00:30 UTC, breville commented on pegasus/sites.v3/code.org/public/alt-about/index.md.erb
> +</a>
Which can also lend the advantage of using HAML instead of HTML for this snippet.

2020-10-02 00:33 UTC, breville commented on pegasus/sites.v3/code.org/public/about/index.erb.md.erb
> +  </object>
This is an interesting technique.  Is there any visual weirdness in any browsers where we see one image load and then the other overrides it?  Or do we always just see one image load?

2020-10-02 00:39 UTC, breville commented
@cforkish Your enthusiasm is enough to justify giving this a go :)  It's worth keeping in mind that we should make sure both the regular and fallback images work for all our supported browsers (particularly IE11, which usually has the most quirks) at all widths (basically desktop, tablet, and mobile).  So it does have the effect of doubling the matrix of things we should validate at least once before merging.  But if you're comfortable with that, then let's give it a try.

I am still a bit curious about how we will feel about supporting these two code paths in a few years' time, and whether we feel this is scalable to all third party badging, but it will be interesting to see.

Also, on the topic of flakiness, do we still think the "v4" version is flaky?

2020-10-07 18:28 UTC, merged