Create button screen reader
code-dot-org/code-dot-org pull request #38761
Opened 2021-01-27 22:52 UTC by epeach

Accessibility work. Part of hackathon project for making nav bar screen reader accessible.

This PR: 
* adds a tab index to the "create" "button" to make it accessible via keyboard navigation.
* adds the ability to expand the "create" 'button' dropdown with an "enter" keypress.

When tested through my local screenreader this allowed me to navigate to a Dance party project through the create button via keyboard navigation and have the button and link text read to me.

Note - it's a best practice for components like this that look like buttons to be HTML button components as some screenreaders can scan a page for just buttons. Out of the scope of this project, but we should consider moving this to be a button tag.

I followed this document to guide these changes: https://a11y-guidelines.orange.com/en/web/components-examples/dropdown-menu/#

# Reviewer Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

2021-01-27 22:55 UTC, annaxuphoto approved these changes
Nice!

2021-01-28 01:25 UTC, annaxuphoto requested changes

2021-01-28 01:25 UTC, annaxuphoto commented on shared/haml/user_header.haml
> +      $('.create_menu').on("keypress click", function(e) {
Can we make another 'return' keypress close the menu?

2021-01-29 18:05 UTC, epeach commented on shared/haml/user_header.haml
> +      $('.create_menu').on("keypress click", function(e) {
Good call! I just added this functionality - PTAL - thanks!

2021-01-29 18:40 UTC, annaxuphoto approved these changes
thanks for updating!

2021-02-02 18:04 UTC, annaxuphoto commented on shared/haml/user_header.haml
> +  %button.header_button.create_menu{tabindex: 0}
I think in this case `tabindex` is redundant since the button should make it tab-able

2021-02-02 18:04 UTC, annaxuphoto commented on shared/haml/user_header.haml
> +          $(document).on('keypress click', (e) => hideCreateOptions(e));
question for my own understanding - what's the difference between the syntax `(e) => hideCreateOptions(e)` and `hideCreateOptions` ?

2021-02-05 21:28 UTC, annaxuphoto approved these changes
LGTM!

2021-02-09 00:13 UTC, merged