ProgressTableSummaryView unit tests
code-dot-org/code-dot-org pull request #38820
Opened 2021-01-29 23:31 UTC by maureensturgeon

- Add ProgressTableSummaryView unit tests
- Fix height of headers (weren't looking right in Chrome)

Fixed:
<img width="1083" alt="Screen Shot 2021-01-29 at 3 30 43 PM" src="https://user-images.githubusercontent.com/24235215/106337783-f5712d80-6246-11eb-8c08-d324ce66b3b8.png">

## Links

- [spec]()
- [jira]()

## Testing story

# Reviewer Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

2021-02-01 18:24 UTC, cforkish requested changes
these look great! however the setup code and initial state looks almost identical to what's in ProgressTableDetailViewTest. would it be possible to move it into the test helper and share it between the two? just keeping with the theme of wanting to limit the amount of test code that needs to be updated if we e.g. modify the redux structure.

2021-02-01 20:03 UTC, maureensturgeon commented on apps/test/unit/templates/sectionProgress/progressTables/ProgressTableSummaryViewTest.jsx
> +const initialState = fakeProgressTableReduxInitialState(
Passing in data instead of having it generated by `fakeProgressTableReduxInitialState` so that it can more easily be referenced in tests below.

2021-02-02 22:42 UTC, cforkish approved these changes
much cleaner, thanks! one additional consolidation you could make would be to move `createStore` into the helper to use by both modules if you feel like it, but i'm cool with this as it is.

2021-02-02 22:42 UTC, cforkish commented on apps/test/unit/templates/sectionProgress/progressTables/ProgressTableSummaryViewTest.jsx
> +const initialState = fakeProgressTableReduxInitialState(
nice trick!

2021-02-02 23:51 UTC, merged