Add line breaks between multiple error/warning messages in debug console
code-dot-org/code-dot-org pull request #47662
Opened 2022-08-16 19:19 UTC by fisher-alice

## Summary
- There are line breaks between multiple error/warning messages when hovering the gutter icon, but line breaks were not included in these messages in the Debug Console. 
- Added line breaks to increase readability when there are multiple errors/warnings displayed in Debug Console.

## Links

- [jira ticket](https://codedotorg.atlassian.net/browse/STAR-2355)

## Testing story

## Deployment strategy

## Follow-up work

## Privacy

## Security

## Caching

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

2022-08-16 19:34 UTC, breville approved these changes

2022-08-16 19:39 UTC, mikeharv requested changes
Thanks for tackling this! I believe this unfortunately introduces a regression that we want to avoid. I pulled and tried out your changes. What I found is that the line break work as expected in the user's console but they are also added to the warnings and errors when hovering over the corresponding symbols in the gutter: 

![image](https://user-images.githubusercontent.com/43474485/184967775-63cbd2cd-468e-4898-bf54-80e66a58cc21.png)

I think the right solution here will involve digging down a layer deeper so that we only add the new line when printing to the console. In other words, `errorString` seems to have the right format, but how we're using varies between the two cases.

2022-08-16 19:54 UTC, breville commented
@mikeharv Excellent catch!

2022-08-16 20:24 UTC, fisher-alice commented
> Thanks for tackling this! I believe this unfortunately introduces a regression that we want to avoid. I pulled and tried out your changes. What I found is that the line break work as expected in the user's console but they are also added to the warnings and errors when hovering over the corresponding symbols in the gutter:
> 
> ![image](https://user-images.githubusercontent.com/43474485/184967775-63cbd2cd-468e-4898-bf54-80e66a58cc21.png)
> 
> I think the right solution here will involve digging down a layer deeper so that we only add the new line when printing to the console. In other words, `errorString` seems to have the right format, but how we're using varies between the two cases.

Thanks so much for catching this!

2022-08-22 16:02 UTC, mikeharv approved these changes
Nice!

2022-08-22 16:35 UTC, merged