serialize start_html_xml using expanded html tags
code-dot-org/code-dot-org pull request #50452
Opened 2023-02-24 22:55 UTC by ebeastlake

## Links

## Testing story

## Deployment strategy

## Follow-up work

## Privacy

## Security

## Caching

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

2023-02-27 21:59 UTC, breville commented
Can we add a unit test to this PR?  It seems the ideal situation for one.

2023-02-27 22:05 UTC, ebeastlake commented
Yes, definitely!

2023-02-28 19:22 UTC, breville commented on dashboard/test/models/levels/blockly_test.rb
> +    start_html = '<div><button id="leftBottomButton" style="padding: 0px; margin: 0px; border-style: solid; background-color: rgb(68, 44, 46); border-radius: 20px; border-width: 0px; border-color: rg
Could we reduce this to a more minimal repro case?  It might be a bit easier to understand what we are verifying...

2023-02-28 21:21 UTC, breville commented on dashboard/app/models/levels/blockly.rb
> +    # TODO: Should we add UTF-8 encoding? We have it here: https://github.com/code-dot-org/code-dot-org/blob/staging/dashboard/app/models/levels/blockly.rb#L520.
nit: can we put the long URL on a new line?

2023-02-28 21:22 UTC, breville approved these changes

2023-02-28 22:13 UTC, mgc1194 requested changes
We should use `Nokogiri::HTML.fragment(start_html,  &:noblanks)` instead of `Nokogiri::XML.fragment(start_html,  &:noblanks)`.
The start_html is a well-formed html fragment that gets injected as into the level document.
It doesn't make sense to use XML here, as it is inducing undesired changes in the html tags (not only creating self-enclosing tags, but closing <img> tags).

2023-02-28 22:15 UTC, ebeastlake commented
Yep, going to change based on our conversation. I don't think we need the argument to `serialize` anymore in this case, but I will confirm.

2023-02-28 22:19 UTC, mgc1194 commented
> 

Exactly.
`start_html_doc.to_html(encoding: 'UTF-8')` should work. We need the `UTF-8` encoding as this localized html will contain characters in any language.

2023-03-01 16:02 UTC, mgc1194 approved these changes
Awesome! This switch to HTML parsing fixes multiple issues. Thanks!

2023-03-01 16:13 UTC, ebeastlake commented
Note: The screenshots in this PR were tested with the original fix, which was replaced with an alternate approach suggested by @mgc1194 (see https://github.com/code-dot-org/code-dot-org/pull/50452/commits/aa37b1a70a0c0b7843970e52be4b883a79280a0a). Most of the screenshots are fixed in the same way, but Mario's approach actually leaves the Order Up! app in an even better state (see below). 

<img width="331" alt="Screen Shot 2023-03-01 at 8 11 30 AM" src="https://user-images.githubusercontent.com/26844240/222197564-c5864626-8814-4476-9af3-ca598d3fe57e.png">

2023-03-01 21:14 UTC, merged