Update Scripts that Launch MySQL Command Line Client
code-dot-org/code-dot-org pull request #50763
Opened 2023-03-14 22:04 UTC by sureshc

## Links

## Testing story

## Deployment strategy

## Follow-up work

## Privacy

## Security

## Caching

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

2023-04-21 17:00 UTC, cat5inthecradle requested changes
Make sure engineers get a heads up on these renames. Consider requesting a review from Dev Tools Working group (has a github group)

This impacts lots of docs too, both in and out of the repo. For example, `SETUP.md` references `bin/dashboard-sql`.

2023-04-21 17:00 UTC, cat5inthecradle commented on aws/cloudformation/components/database.yml.erb
> +      DebugLogging: true
delete or add deletion criteria?

2023-07-19 22:16 UTC, sureshc commented
@code-dot-org/dev-tools-group Thoughts on the new names for these scripts that launch they MySQL client? My intention here is to:

-  give them names that explain what they actually do so we don't have to document that they exist to new engineers (we have a half dozen Google docs that tell engineers about these scripts)
- use a naming convention that ensures they are all displayed together when listed alphabetically
- use a hierarchical naming convention so that engineers can easily discover full range of options available to them

I'm considering combining this into a single script (`bin/mysq-client`) which would:

- Default to connecting as admin directly to the writer endpoint in development and adhoc environments
- Default to connecting to dashboard with the reader user to the reader proxy endpoint on test
- Default to connecting to dashboard with the reader user to the reporting proxy endpoint on production (reporting endpoint ensures long running queries don't impact production performance).
- Present interactive options to select a different option (writer user, writer endpoint, etc.) and/or accept command line arguments to override the above defaults.

2023-07-19 22:55 UTC, davidsbailey commented
> * Present interactive options to select a different option (writer user, writer endpoint, etc.) and/or accept command line arguments to override the above defaults.

I like the proposal in general. If you go the single script option, I would personally advocate for command line options over interactive options, unless the interactive options can be avoided/overridden by specifying the corresponding command line options (don't get me started on how many adhocs I've started and then failed to press `y`).

2023-08-01 19:28 UTC, Hamms reviewed
Renames sound good to me, new secrets look right, and I like the plan for next steps!

Are we worried about any chicken-and-egg problems here? I know it was necessary for us to add the new options with placeholder values first, but It's not clear to me whether or not it's necessary for us to break up into multiple PRs the three steps of enabling the new options with `!StackSecret`, using them instead of the old options, and removing the old options.

2023-08-01 19:48 UTC, sureshc commented
> Are we worried about any chicken-and-egg problems here? I know it was necessary for us to add the new options with placeholder values first, but It's not clear to me whether or not it's necessary for us to break up into multiple PRs the three steps of enabling the new options with `!StackSecret`, using them instead of the old options, and removing the old options.

Because the old `CDO.` configuration settings populated from `!Secrets` and the new `CDO.` settings populated from `!StackSecrets` are ONLY referenced by the MySQL client scripts, we don't have any circular-dependency issues with this change. But, yes, typically we would have to deploy the new config settings in one Pull Request, then a separate change to start using them, and then a third change to remove the old settings.

2023-08-01 21:09 UTC, sureshc commented
@cat5inthecradle Are the changes you requested resolved?

2023-08-02 18:09 UTC, cat5inthecradle approved these changes

2023-08-02 18:10 UTC, merged