Update code.org/ai blue banner
code-dot-org/code-dot-org pull request #52961
Opened 2023-07-24 15:05 UTC by dmantonyuk

## Links
https://codedotorg.atlassian.net/browse/ACQ-699
https://code.org/ai

## Testing story

## Deployment strategy

## Follow-up work

## Privacy

## Security

## Caching

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

2023-07-24 20:49 UTC, kelbyhawn commented on pegasus/sites.v3/code.org/public/ai/index.haml
> +      %a.link-button{href: "/ai/pl/101", target: "_blank", rel: "noopener noreferrer"}=hoc_s(:signup_submit_explore)
Since this page is on our site you can remove the `target: "_blank", rel: "noopener noreferrer"` here.

2023-07-24 20:51 UTC, kelbyhawn requested changes
Left one comment, but otherwise looks great!

2023-07-25 15:32 UTC, dmantonyuk commented
@kelbyhawn  please check one more time

2023-07-25 19:05 UTC, kelbyhawn approved these changes

2023-07-26 10:30 UTC, merged