adding parental_permissions_requests
code-dot-org/code-dot-org pull request #53584
Opened 2023-09-01 16:29 UTC by jordan-springer

Adding table to DMS task

## Links

- spec: []()
- jira ticket: [https://codedotorg.atlassian.net/browse/DATAOPS-219](DATAOPS-219)

## Testing story

## Deployment strategy

## Follow-up work

[CPA Metrics report(https://codedotorg.atlassian.net/browse/P20-330)

## Privacy
Didn't see any pii fields other than `parent_email`, idk if you want to remove that or not

## Security

## Caching

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

2023-09-01 16:32 UTC, carl-codeorg commented
Does this table need to be under cron-pii if we aren't doing a "remove column" on parent_email?

2023-09-01 16:34 UTC, jordan-springer commented on aws/dms/tasks.yml
> +- dashboard.parental_permission_requests
@carl-codeorg is this not under the `cron` job? are you saying it _should_ be under the `cron_pii`?...

2023-09-05 15:08 UTC, carl-codeorg commented on aws/dms/tasks.yml
> +- dashboard.parental_permission_requests
Oh I only mentioned this because I saw that there are separate Redshift dbs called dashboard and dashboard_pii - I thought these jobs might correspond to those dbs. If this yaml file is unrelated then just ignore my comment.

2023-09-08 18:22 UTC, Hamms commented
+1 to Carl's comment; `parent_email` definitely looks like PII to me

2023-09-08 19:11 UTC, pablo-code-org commented
Is it PII if it is hashed? I don't know if that column is hashed.

2023-09-08 19:17 UTC, carl-codeorg commented
> Is it PII if it is hashed? I don't know if that column is hashed.

This column isn't hashed like student emails are.

2023-09-08 19:26 UTC, cat5inthecradle commented
Sorry for the delay in acting on this, I think we have some unclear processes and unclear systems. I will connect with the folks involved in this PR in slack form additional discussion.

2023-09-18 16:40 UTC, jordan-springer commented
@cat5inthecradle what's the status here?

2023-09-18 23:09 UTC, cat5inthecradle requested changes

2023-09-18 23:09 UTC, cat5inthecradle commented on aws/dms/tasks.yml
> +- dashboard.parental_permission_requests
This table contains PII. Can we either exclude the PII columns from the DMS export, or provide justification in this PR or the Jira ticket for extracting the PII fields from the primary database?

2023-09-19 15:31 UTC, cat5inthecradle commented on aws/dms/tasks.yml
> +- dashboard.parental_permission_requests
I think this should cover it. By removing the unneded `parent_email` this table is safe to load into the `dashboard` non-pii schema.

```suggestion
- dashboard.parental_permission_requests:
    remove_column: [parent_email]
```

2023-09-19 17:25 UTC, cat5inthecradle approved these changes

2023-09-19 18:00 UTC, sureshc commented
I deployed these changes from my workstation using admin credentials and the `stack:data:start` rake task at 10:50 AM PDT today. You can merge this change now.

2023-09-19 18:10 UTC, merged