Disable Deprecated MySQL Client Reconnect
code-dot-org/code-dot-org pull request #54395
Opened 2023-10-20 21:53 UTC by sureshc

We've recently upgraded our web application server and daemon EC2 Instances from Ubuntu 18 to Ubuntu 20 and now use the MySQL 8 client. The new MySQL 8 client (which is backwards compatible with the MySQL 5.7 server that we are using) logs to Standard Output: `WARNING: MYSQL_OPT_RECONNECT is deprecated and will be removed in a future version.` because we have this client feature enabled in both Pegasus and Dashboard.

Disable MySQL client reconnect because we likely don't rely on it.

- Our dashboard and pegasus web application servers connect to ProxySQL running locally on the same instance, so a connection failure is unlikely, and also the latest release of ProxySQL [doesn't support MYSQL_OPT_RECONNECT](https://proxysql.com/documentation/global-variables/mysql-variables/#mysql-default_reconnect) and the fork of an older release of ProxySQL [that we use](https://github.com/wjordan/proxysql/tree/v2.0.8) doesn't seem to use the MySQL client reconnect feature.
- [Pegasus connection adapter](https://github.com/code-dot-org/code-dot-org/blob/b43061474de78b2641495fa232938a7115e6ae58/lib/cdo/db.rb#L30-L36) and [Database connection adapter](https://github.com/code-dot-org/code-dot-org/blob/b43061474de78b2641495fa232938a7115e6ae58/dashboard/config/database.yml#L21) are configured to manage a pool of connections that automatically open new connections when existing connections in the pool are terminated/disrupted.

## Testing story

## Deployment strategy

## Follow-up work

## Privacy

## Security

## Caching

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

2023-10-20 21:56 UTC, Hamms approved these changes
LGTM! Thanks for the detailed investigation notes

2023-10-23 16:51 UTC, sureshc commented
A unit test failed due to a database connection opened by Sequel getting disconnected. I'm wondering if we need to add the `:connection_validator` [Sequel extension](http://sequel.jeremyevans.net/rdoc-plugins/files/lib/sequel/extensions/connection_validator_rb.html).

2023-11-03 19:36 UTC, pablo-code-org commented on dashboard/config/database.yml
> +  # reconnect: false
why not removing it completely?

2023-11-03 19:38 UTC, pablo-code-org requested changes
I am rejecting so it gets attention to the questions I just asked, not because there is anything wrong :) 

Thanks for doing this!

2023-11-03 19:38 UTC, pablo-code-org commented on lib/cdo/db.rb
> +    # http://sequel.jeremyevans.net/rdoc-plugins/files/lib/sequel/extensions/connection_validator_rb.html
why is this added?

2023-11-03 19:38 UTC, pablo-code-org commented on lib/cdo/db.rb
> +  # https://sequel.jeremyevans.net/rdoc-plugins/files/lib/sequel/extensions/server_block_rb.html
why is this added?

2023-11-27 22:58 UTC, Hamms commented
Based on the CI errors, it seems like we will want to implement some alternative reconnection logic to replace the deprecated functionality we're disabling. I'm not sure how best to achieve that for ActiveRecord connections.

For Sequel, [the existing `validation_frequency` setting](https://github.com/code-dot-org/code-dot-org/blob/15f897a6b98051f3012b4b2b6f4c152a0ce0a899/lib/cdo/db.rb#L80-L85) is probably what we want; local testing indicates that setting that to `-1` so that we always validate connections on checkout is sufficient to get the tests passing. I'm not sure what value we want to use in production.

2024-02-03 05:29 UTC, closed without merging

2024-03-25 18:06 UTC, sureshc commented
Re-opened post git-lfs migration  in #57507