Update code.org/youngwomen page to indicate that applications are now closed
code-dot-org/code-dot-org pull request #55218
Opened 2023-11-29 18:16 UTC by kelbyhawn

TBD

**Jira ticket:** [ACQ-1184](https://codedotorg.atlassian.net/browse/ACQ-1184)

----

## Before

## After

2023-11-29 18:42 UTC, kelbyhawn commented on pegasus/sites.v3/code.org/public/css/page/young-women-in-cs-styles.scss
> +      background-image: url("/images/yw-page-top.png"), url("/images/banners/banner-bg-mesh-dots-light.png");
The background pattern image was showing through the photo of the young women, so I swapped them to fix the transparency issue.

| Before | After |
|--------|-------|
| <img width="180" alt="Before" src="https://github.com/code-dot-org/code-dot-org/assets/9256643/f38bf63f-694b-42fb-9153-2050d2e3ca4b"> | <img width="180" alt="After" src="https://github.com/code-dot-org/code-dot-org/assets/9256643/339cf272-0d62-4555-8708-06da6a60dba4"> |

2023-11-29 18:59 UTC, dmcavoy commented
Changes look good to me

2023-11-29 19:34 UTC, bethanyaconnor approved these changes

2023-11-30 17:18 UTC, jmkulwik approved these changes

2023-11-30 17:18 UTC, cat5inthecradle requested changes
approved pending rebase on staging

2023-11-30 18:04 UTC, cat5inthecradle approved these changes

2023-11-30 18:06 UTC, merged