Add ssl flag to thin during local https development
code-dot-org/code-dot-org pull request #58821
Opened 2024-05-21 20:18 UTC by carl-codeorg

Sometimes it's necessary to use https for local development. Even with the `https_development` flag set to true, the `ssl` option still has to be passed to `thin` when running the server locally. This changes `bin/dashboard-server` to automatically append --ssl if `https_development` is true and the environment is `:development`.

## Links

## Testing story

Tested locally. If there are already tests in place for the bin directory, let me know.

## Deployment strategy

## Follow-up work

## Privacy

## Security

## Caching

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

2024-05-21 21:13 UTC, stephenliang approved these changes

2024-05-21 21:33 UTC, nicklathe approved these changes

2024-05-21 22:32 UTC, daynew requested changes
`locals.yml.default` should have a commented out config with documentation added.

2024-05-21 23:05 UTC, daynew approved these changes

2024-05-22 18:17 UTC, sureshc approved these changes
Follow up for Infrastructure Team … we should probably switch from `thin` to `puma` for development environments, since that’s the default rack server for Rails now.

2024-05-22 18:24 UTC, merged