P20-990: Fix Policy Compliance UI tests
code-dot-org/code-dot-org pull request #59719
Opened 2024-07-11 13:28 UTC by artem-vavilov

## Links:
- JIRA task: [P20-990](https://codedotorg.atlassian.net/browse/P20-990)

2024-07-16 16:21 UTC, wilkie commented on dashboard/test/ui/features/platform/policy_compliance.feature
> +    Given I create a teacher who has never signed in named "AMDTrad Teacher" after CPA exception and go home
Haha. I thought maybe you were rebelling against my use of 80s computer models as my user naming scheme in this file until I realized what happened here. 😂

2024-07-16 16:24 UTC, wilkie approved these changes
Your mst -> mdt substitution hit a username 😂 but otherwise this all looks great and I'm very happy to see the DCDO mocking being used very very effectively here.

2024-07-16 17:55 UTC, artem-vavilov commented on dashboard/test/ui/features/platform/policy_compliance.feature
> +    Given I create a teacher who has never signed in named "AMDTrad Teacher" after CPA exception and go home
Sorry, I'll fix this!

2024-07-17 20:17 UTC, wilkie approved these changes

2024-07-17 20:18 UTC, wilkie requested changes
Just to remember to remove the console.logs

2024-07-17 21:32 UTC, wilkie approved these changes

2024-07-17 22:33 UTC, merged